[package]
name = "farmbot"
version = "0.1.0"
authors = ["connor rigby <konnorrigby@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"